### ISSUE TITLE
Call to undefined function League\Uri\Components\idn_to_ascii()

### ISSUE THREAD

**Issue by duxthefux** [AuraEQ/fire-and-forget#1]
Hey, 

I think you just created a new bug with newest version 0.1.6
<img width="1226" alt="bildschirmfoto 2015-12-13 um 21 34 31" src="https://cloud.githubusercontent.com/assets/6758162/11769176/682587ee-a1e1-11e5-8000-3d850d7e537c.png">

Am I right?

Regards!

---edit
sorry my fault, extension was missing

**Comment by hipsterjazzbo** [comment]
Yeah, the new version of `league/uri` requires the `intl` extension :)

**Comment by duxthefux** [comment]
Hey thanks!

Anyway I just found out that fire and forget os not working properly anymore. I use it for posting an url to trigger push notifications.

When I post() with fire and forget its not working at all but I'm pretty sure that the previous version worked :/

Thanks!
